strains_list = ['22', '999', '1024', '100 og', '12 year og', '13 dawgs',
       '24k gold', '3 bears og', '3 kings', '303 og', '3d cbd',
       '3rd coast panama chunk', '3x crazy', '501st og', '541 kush',
       '5th element', '707 headband', '707 truthband', '8 ball kush',
       '818 og', '831 og', '9 pound hammer', '91 krypt', 'aberdeen',
       'abusive og', 'acapulco gold', 'acdc', 'ace killer og',
       'ace of spades', 'aceh', 'acid', 'acid dough', 'afcrack',
       'afghan big bud', 'afghan cow', 'afghan diesel', 'afghan hawaiian',
       'afghan haze', 'afghan kush', 'afghan skunk', 'afghan sour kush',
       'afghan widow', 'afghani', 'afghani bullrider', 'afghani cbd',
       'afghani krush', 'afghanica', 'afghanimal', 'afgoo', 'afgooey',
       'afkansastan', 'afpak', 'african', 'afrodite', 'afternoon delight',
       'afwreck', 'agape', 'agent orange', 'agent tangie',
       'air jordan og', 'alaska', 'alaska thunder grape', 'alaskan ice',
       'alaskan thunder fuck', 'albert walker', 'alchemy', 'alf',
       'alice in wonderland', 'alien abduction', 'alien apparition',
       'alien asshat', 'alien breath', 'alien bubba', 'alien dawg',
       'alien dutchess', 'alien hallucination', 'alien inferno',
       'alien kush', 'alien og', 'alien reunion', 'alien rift',
       'alien rock candy', 'alien sour apple', 'alien stardawg',
       'alien technology', 'alien walker', 'aliens on moonshine',
       'allen iverson og', 'allen wrench', 'alley cat kush', 'allkush',
       'aloha', 'aloha grape stomper', 'aloha limone', 'alohaberry',
       'alpha blue', 'alpha express', 'alpha og', 'alpine blue',
       'alpine star', 'als dream', 'altoyd', 'ambrosia',
       'american beauty', 'american dream', 'american kush',
       'american pie', 'americano', 'amethyst', 'amethyst bud',
       'amherst sour diesel', 'amnesia', 'amnesia ganja haze',
       'amnesia haze', 'amnesia og', 'ancient kush', 'ancient og',
       'anesthesia', 'angel og', 'animal blues', 'animal gas',
       'animal mint', 'animal sherbert', 'anonymous og', 'anubis',
       'ape shit', 'apollo 11', 'apollo 13', 'apollo 13 haze',
       'apollo haze', 'appalachia', 'appalachian power', 'apple jack',
       'apple kush', 'appleberry', 'arabian gold', 'arctic sun',
       'arcticblue', 'area 51', 'argyle', 'arjans strawberry haze',
       'arjans ultra haze 1', 'armageddon', 'armagnac', 'ash',
       'asian fantasy', 'aspen og', 'astral works', 'astroboy',
       'athabasca', 'atmosphere', 'atomic', 'atomic goat',
       'atomic northern lights', 'atomical haze', 'aurora borealis',
       'aurora indica', 'avalon', 'avi', 'ayahuasca purple', 'azure haze',
       'b4', 'bakerstreet', 'balmoral', 'banana bread', 'banana candy',
       'banana cream og', 'banana diesel', 'banana hammock r1',
       'banana kush', 'banana og', 'banana peel', 'banana punch 9',
       'banana split', 'bananas', 'bandana', 'bangi haze', 'bango',
       'banjo', 'barbara bud', 'batgirl', 'batman og', 'bay 11',
       'bay dream', 'bazooka joe g', 'bb king', 'bc big bud',
       'bc roadkill', 'bc sweet tooth', 'bear dance', 'beastmode og',
       'beckwourth bud', 'bedford glue', 'bedica', 'bediol',
       'bell ringer', 'belladonna', 'berkeley', 'bermuda sour',
       'berry bomb', 'berry larry', 'berry noir', 'berry og',
       'berry white', 'bertberry cheesecake', 'berts cookie dough',
       'best friend og', 'bettie page', 'bianca', 'biddy early',
       'big band', 'big bang', 'big bud', 'big buddha cheese', 'big bull',
       'big holy nina', 'big kush', 'big mac', 'big skunk korean',
       'big sky og', 'big smooth', 'big sur holy bud', 'big white',
       'big wreck', 'biker kush', 'biker leblanc', 'bingo pajamas',
       'biochem', 'biohazard', 'birds eye', 'birds of paradise',
       'birthday cake kush', 'black 84', 'black afghan', 'black betty',
       'black bubba', 'black cheese', 'black cherry cheesecake',
       'black cherry og', 'black cherry pie', 'black cherry soda',
       'black dahlia', 'black diamond', 'black diesel', 'black dog',
       'black domina', 'black haze', 'black ice', 'black jack',
       'black label', 'black label kush', 'black lime special reserve',
       'black lotus', 'black magic', 'black magic kush', 'black mamba',
       'black out', 'black raspberry', 'black roses', 'black russian',
       'black triangle', 'black tuna', 'black velvet', 'black widow',
       'blackberry', 'blackberry bubble', 'blackberry chem og',
       'blackberry cream', 'blackberry diesel', 'blackberry dream',
       'blackberry fire', 'blackberry hashplant', 'blackberry haze',
       'blackberry kush', 'blackberry lime haze', 'blackberry pie',
       'blackberry rhino', 'blackberry snow cone',
       'blackberry trainwreck', 'blackberry x blueberry', 'blackwater',
       'blaze', 'bleugenius', 'blissful wizard', 'blizzard bush',
       'blob og', 'blockhead', 'blood orange kush', 'bloodhound',
       'bloodwalker', 'bloos kloos', 'blowfish', 'blucifer',
       'blue afghani', 'blue alien', 'blue bastard', 'blue bayou',
       'blue blood', 'blue boy', 'blue buddha', 'blue champagne',
       'blue cheese', 'blue cinex', 'blue cookies', 'blue crack',
       'blue diamond', 'blue diesel', 'blue dot', 'blue dragon',
       'blue dream', 'blue dream cbd', 'blue dynamite', 'blue fire',
       'blue frost', 'blue galaxy', 'blue god', 'blue goo', 'blue hash',
       'blue hawaiian', 'blue haze', 'blue heron', 'blue iguana',
       'blue ivy', 'blue j', 'blue jay way', 'blue kiss', 'blue knight',
       'blue kripple', 'blue kush', 'blue lights', 'blue magic',
       'blue magoo', 'blue monster', 'blue moon rocks', 'blue moonshine',
       'blue mountain fire', 'blue mystic', 'blue nightmare', 'blue nina',
       'blue og', 'blue og sherbert', 'blue ox', 'blue persuasion',
       'blue power', 'blue raspberry snow cone', 'blue rhino',
       'blue satellite', 'blue sherbert', 'blue sky', 'blue steel',
       'blue thai', 'blue trainwreck', 'blue treat', 'blue velvet',
       'blue venom', 'blue widow', 'blue wolf', 'blue wonder',
       'blue wreck', 'blue zkittlez', 'blue zombie', 'blueberry',
       'blueberry ak', 'blueberry blast', 'blueberry bomb',
       'blueberry diesel', 'blueberry dream', 'blueberry essence',
       'blueberry hashplant', 'blueberry haze', 'blueberry headband',
       'blueberry jack', 'blueberry kush', 'blueberry lambsbread',
       'blueberry muffin', 'blueberry og', 'blueberry pancakes',
       'blueberry pie', 'blueberry silvertip', 'blueberry skunk',
       'blueberry space cake', 'blueberry triple og', 'blueberry waltz',
       'blueberry yum yum', 'blues', 'blukashima', 'bluniverse',
       'blurple', 'blush', 'bob saget', 'bodega bubblegum',
       'bog blue kush', 'bog bubble', 'bog sour grape', 'bogart',
       'boggle gum', 'bona dea', 'bonkers', 'booger', 'boombaye',
       'bootlegger', 'bootylicious', 'bordello', 'boss hogg', 'boss og',
       'brain candy', 'brains damage', 'brainstorm haze', 'brainwreck',
       'brand x', 'brandywine', 'brazil amazonia', 'brian berry cough',
       'bright fire', 'bright moments', 'broke diesel', 'bronze whaler',
       'brooklyn mango', 'bruce banner', 'bruce banner 3', 'bsc',
       'bubba berry', 'bubba doja', 'bubba fresh', 'bubba kush',
       'bubba og', 'bubba tom hayes', 'bubba x skunk', 'bubbas bitch',
       'bubbas gift', 'bubble bomb', 'bubble cheese', 'bubble gum',
       'bubbleberry', 'bubblegum kush', 'bubblegun', 'bubblicious',
       'buckeye purple', 'buddha haze', 'buddha tahoe', 'buddhas hand',
       'buddhas sister', 'buddhas tooth', 'buffalo bill', 'bugatti og',
       'burkle', 'burmese kush', 'burnt cookies', 'butter og',
       'butterscotch', 'c13 haze', 'c3', 'c3po', 'c4', 'cabbage patch',
       'cackleberry', 'cactus', 'cactus cooler', 'cadillac cookies',
       'cadillac purple', 'cali dragon', 'cali gold', 'cali jack',
       'cali kush', 'california grapefruit', 'california hash plant',
       'california limes', 'california love og', 'california orange',
       'california sour', 'california sour diesel', 'cambodian',
       'cambodian haze', 'candy apple', 'candy cane', 'candy jack',
       'candyland', 'cannadential', 'cannalope haze', 'cannalope kush',
       'cannasutra', 'cannatonic', 'capers', 'capleton',
       'captain america og', 'captains cake', 'caramel cake',
       'caramel candy kush', 'caramel kona coffee cookies',
       'caramel kona coffee kush', 'caramelicious', 'caramella',
       'caramelo', 'carl sagan', 'carmel cough', 'carnival',
       'carpet tape', 'cascadia kush', 'casey jones', 'cashus clay',
       'casper og', 'cat piss', 'cataract kush', 'catfish',
       'cbd blue shark', 'cbd critical cure', 'cbd critical mass',
       'cbd kush', 'cbd lilly', 'cbd og', 'cbd ox', 'cbd rich blessing',
       'cbd shark', 'cello sweet og', 'central american', 'cerebro haze',
       'chairman chem sou', 'champagne diesel', 'champagne kush',
       'charlie sheen', 'charlottes web', 'cheese', 'cheese candy',
       'cheeseburger', 'cheesewreck', 'chef kush', 'chem berry diesel',
       'chem beyond diesel cbd', 'chem crush', 'chem jack',
       'chem jong ill', 'chem scout', 'chem valley kush', 'chemd.o.g',
       'chemdawg sour diesel', 'chemdog', 'chemdog 4',
       'chemdog 4xalien og kush', 'chemdog 91', 'chemmy jones',
       'chemnesia', 'chemo', 'chems sister', 'chemwreck', 'chernobyl',
       'cherries jubilee', 'cherry bomb', 'cherry cookies',
       'cherry cream pie', 'cherry diesel', 'cherry durban poison',
       'cherry fire', 'cherry fuel', 'cherry grapefruit', 'cherry kola',
       'cherry kush', 'cherry limeade', 'cherry mender', 'cherry og',
       'cherry pie', 'cherry pie kush', 'cherry sauce', 'cherry sherbet',
       'cherry skunk', 'cherry slyder', 'cherry thunder fuck',
       'cherry vanilla cookies', 'cherry wine', 'cherwillie', 'chicle',
       'chiesel', 'china yunnan', 'chiquita banana', 'chloe',
       'chocoholic', 'chocolate cheesecake', 'chocolate chunk',
       'chocolate diesel', 'chocolate drop', 'chocolate fondue',
       'chocolate glue', 'chocolate hashberry', 'chocolate kush',
       'chocolate lava', 'chocolate mint og', 'chocolate og',
       'chocolate rain', 'chocolate sap', 'chocolate skunk',
       'chocolate thai', 'chocolate thunder', 'chocolope kush',
       'chong star', 'chr super og', 'chronic', 'chronic thunder',
       'chuck og', 'chuckys bride', 'chunky diesel', 'chupacabra',
       'church og', 'cinderella 99', 'cinderellas dream', 'cindy white',
       'cinex', 'cirrus', 'citradelic sunset', 'citral glue',
       'citral skunk', 'citrix', 'citrus kush', 'citrus punch',
       'citrus rush', 'citrus sap', 'citrus sunshine haze', 'city of god',
       'clementine', 'clementine kush', 'clementines terpentine',
       'clockwork orange', 'cloud 9', 'cloudcap', 'club 69',
       'cluster bomb', 'cobra lips', 'coconut oil', 'cold creek kush',
       'colin og s1', 'colombian gold', 'colombian mojito',
       'colorado bubba', 'colorado chem', 'colorado clementines',
       'commerce city kush', 'concord cream', 'concord grape blockhead',
       'confidential cheese', 'confidential cookies',
       'confidential wreck', 'congo', 'connie chung', 'conspiracy kush',
       'cookie breath', 'cookie dough', 'cookie jar', 'cookie monster',
       'cookie puss', 'cookie wreck', 'cookies and dream', 'copper kush',
       'corleone kush', 'corleone kush the don cut', 'cornbread',
       'cosmic collision', 'cotton candy kush', 'cotton purple chem',
       'cougar milk', 'cowboy kush', 'coyote art', 'cracker jack',
       'crater lake', 'crazy miss hyde', 'cream caramel', 'crimea blue',
       'critical 47', 'critical bilbo', 'critical cheese',
       'critical haze', 'critical hog', 'critical jack',
       'critical kali mist', 'critical kush', 'critical mass',
       'critical plus', 'critical plus 20', 'critical sensi star',
       'critical skunk', 'critical widow', 'critters cookies',
       'crocketts haze', 'cronuts', 'crosswalker',
       'crouching tiger hidden alien', 'crown og', 'crown royale',
       'crumbled lime', 'crunch berry kush', 'crypt', 'crystal coma',
       'crystal gayle', 'crystalberry', 'csg', 'cuvee', 'cypress og',
       'dairy queen', 'dakini  kush', 'damn sour', 'damnesia',
       'dance world', 'dancehall', 'dank schrader', 'dank sinatra',
       'danky doodle', 'dark blue dream', 'dark shadow haze',
       'dark side of the moon', 'dark star', 'darkside og',
       'darth vader og', 'dawgfather og', 'dawgs waltz', 'day tripper',
       'daywalker', 'deadhead og', 'deadlights', 'deadwood',
       'death bubba', 'death by cake og', 'death star', 'deep breath',
       'deep cheese', 'deep chunk', 'deep purple', 'deep sleep',
       'delahaze', 'denver maple', 'desert diesel', 'desert star',
       'destroyer', 'devil fruit', 'devils tit', 'diablo', 'diamond og',
       'diamond socks', 'diamond valley kush', 'diesel dough',
       'diesel duff', 'diesel glue', 'dieseltonic', 'digweed', 'dinachem',
       'dirty girl', 'dirty old bastard', 'dirty widow', 'disney blue',
       'divina obscura', 'dizzy og', 'dj andy williams',
       'dj short blueberry', 'dj smoke', 'django', 'doc holliday',
       'doctor doctor', 'dog shit', 'dogwalker og', 'dolla sign og kush',
       'domino', 'don carlos', 'don shula', 'donegal', 'donkey butter',
       'donna og', 'dons ghost', 'doobiebird daydream', 'doox', 'dopium',
       'dorit', 'double barrel og', 'double diesel', 'double dream',
       'double dutch', 'double mint', 'double og', 'double purple doja',
       'double tangie banana', 'double tap', 'dougs varin', 'dr feelgood',
       'dr funk', 'dr grinspoon', 'dr quantum', 'dr who', 'dragon fruit',
       'dragon og', 'dragon punch', 'dragons breath', 'dreadlock',
       'dream beaver', 'dream berry', 'dream girl', 'dream lotus',
       'dream machine', 'dream police', 'dream queen', 'dream star',
       'dreamcatcher', 'drizella', 'duct tape', 'duke nukem',
       'durban berry', 'durban cheese', 'durban cookies', 'durban poison',
       'durban princess', 'durga mata', 'dutch crunch', 'dutch dragon',
       'dutch hawaiian', 'dutch haze', 'dutch kush', 'dutch queen',
       'dutch thunder fuck', 'dutch treat', 'dutch treat haze',
       'dutchberry', 'dynamite', 'eagle bill', 'early girl',
       'early glue rbx1', 'early miss', 'early pearl', 'early skunk',
       'earth og', 'earthquake', 'earthshaker og', 'east coast alien',
       'east coast sour diesel', 'eastern european', 'easy bud',
       'easy peezy', 'ebola 7', 'ecto cooler', 'ed rosenthal super bud',
       'edelweiss', 'egyptian royalty 1', 'el chapo', 'el chapo og',
       'el jefe', 'el perro', 'elderberry kush', 'electric black mamba',
       'electric kool aid', 'electric lemon g', 'electric lemonade',
       'elektra', 'elephant', 'elmers glue', 'elphinstone', 'elvis',
       'emerald jack', 'emerald og', 'emperor cookie dough',
       'endless sky', 'enemy of the state', 'enigma', 'eran almog',
       'erez', 'ether', 'ethiopian', 'ethos hash plant bx1', 'euforia',
       'eugene cream', 'euphoria cookies', 'everlast', 'exodus cheese',
       'extreme cream', 'extreme og', 'f 13', 'face off bx2',
       'face off og', 'face on fire', 'faded glory', 'fallen angel',
       'false teeth', 'fast eddy', 'fat axl', 'fat nelson', 'fat purple',
       'fauxsido', 'faygo red pop', 'fighting buddha', 'fire alien kush',
       'fire alien strawberry', 'fire haze', 'fire og', 'firewalker og',
       'first 48', 'first light', 'flaming cookies', 'flo', 'flo limone',
       'flo og', 'flo walker', 'florida og', 'flowerbomb kush',
       'flowers for algernon', 'fn louzer', 'forbidden fruit',
       'forbidden zkittlez', 'formula one', 'fortune cookies',
       'forum cut cookies s1', 'foul mouth', 'four cups',
       'four star general', 'four way', 'fpog', 'frankenstein',
       'franks gift', 'fred flipn stoned', 'freezeland', 'french bread',
       'frida', 'frisian dew', 'frisian duck', 'frostbite',
       'frosted cherry cookies', 'frosted freak', 'frosty',
       'frosty jesus', 'fruit crusher', 'fruit loops', 'fruit punch',
       'fruit spirit', 'fruity chronic juice', 'fruity juice',
       'fruity widow', 'fruitylicious', 'fucking incredible', 'full moon',
       'funfetti', 'funky monkey', 'future', 'g13 diesel', 'g13 haze',
       'g13 widow', 'gabriel sherbet', 'galactic jack', 'galactica og',
       'game changer', 'gandalf og', 'ganesh berry', 'garlic bud',
       'gas mask', 'gatekeeper og', 'gdp electric', 'gelato', 'gelato 33',
       'gemstone', 'georgia pine', 'ghost bubba', 'ghost cookies',
       'ghost og', 'ghost og moonshine', 'ghost rider og', 'ghost ship',
       'ghost train haze', 'ghostbreath', 'gigabud', 'gilz nilz',
       'ginger ale', 'ginger punch', 'glad max', 'glass apple',
       'glass slipper', 'glue tech', 'gluechee', 'gmo cookies',
       'gnome walker', 'go time', 'goat', 'goat head', 'gobbilygoo',
       'gobbstopper', 'god bud', 'godberry', 'godfather og',
       'godfather purple kush', 'gods bubba', 'gods green crack',
       'gods treat', 'godzilla', 'godzilla blood', 'godzilla glue',
       'goji diesel', 'goji og', 'gold kings thai', 'goldberry',
       'golden calyx', 'golden gage', 'golden goat', 'golden lemon',
       'golden nugget', 'golden panda', 'golden pineapple',
       'golden state banana', 'golden tangie', 'golden ticket',
       'golden tiger', 'goldwing', 'goo', 'gooberry', 'good medicine',
       'gorilla biscuit', 'gorilla breath', 'gorilla cookies',
       'gorilla girl', 'gorilla grips', 'gorilla snacks', 'gorkle',
       'government mule', 'grand doggy purps', 'grand hindu',
       'grand hustle', 'granddaddy purple', 'grandma andersons cookies',
       'grandmas batch', 'grandmas sugar cookies', 'grandpa larry og',
       'granola funk', 'grape ape', 'grape bubba', 'grape calyx',
       'grape cookies', 'grape dawg', 'grape drink', 'grape god',
       'grape inferno', 'grape jelly', 'grape krush', 'grape kush',
       'grape ox', 'grape skunk', 'grape soda', 'grape stomper',
       'grape valley kush', 'grape vine', 'grapefruit',
       'grapefruit diesel', 'grapefruit haze', 'grapefruit kush',
       'gravity', 'grease monkey', 'green avenger', 'green candy',
       'green cheese', 'green crack', 'green crack cbd',
       'green crack extreme', 'green door kush', 'green dragon',
       'green dream', 'green goblin', 'green goddess', 'green haze',
       'green hornet', 'green kush', 'green lantern', 'green line og',
       'green love potion', 'green magic', 'green mango', 'green monster',
       'green poison', 'green python', 'green queen', 'green ribbon',
       'gremlin', 'grilled cheese', 'grimace', 'grimace og', 'grimmdica',
       'griz kush', 'gsc', 'gto', 'guard dawg', 'guava cake',
       'guava chem', 'guava gelato', 'guava kush', 'gucci og',
       'guido kush', 'gumbo', 'gummo', 'gummy bears', 'gupta haze',
       'gupta kush', 'guptilla', 'gutbuster', 'hades haze', 'hades og',
       'hammerhead', 'hannibal nectar', 'haole', 'haoma', 'haoma mist',
       'happy rancher', 'hardcore og', 'harlequin', 'harlequin gdp',
       'harley storm', 'harley twin', 'harmonia', 'harmony',
       'harry potter', 'hash plant', 'hashbar og', 'hashberry',
       'hashplant haze', 'hawaiian', 'hawaiian cookies',
       'hawaiian delight', 'hawaiian diesel', 'hawaiian dream',
       'hawaiian duckfoot', 'hawaiian fire', 'hawaiian haze',
       'hawaiian mayan gold', 'hawaiian punch', 'hawaiian purple kush',
       'hawaiian sativa', 'hawaiian skunk', 'hawaiian snow',
       'hawaiian sunrise', 'hawaiian thunder fuck', 'hawaiian trinity',
       'hayleys haze', 'haze', 'haze berry', 'haze heaven', 'haze mist',
       'haze wreck', 'hazmat og', 'head cheese', 'head trip', 'headband',
       'headbanger', 'heatwave', 'heaven scent', 'heavenly og',
       'heavy duty fruity', 'heisenberg kush', 'hell raiser og',
       'hellfire og', 'hells og', 'hemlock', 'hempstar', 'hercules',
       'herijuana', 'hibiscus sunrise', 'high noon irish cream',
       'high school sweetheart', 'higher power', 'highwayman',
       'himalayan blackberry', 'himalayan gold', 'hindu kush',
       'hindu skunk', 'hindu sour', 'hippie chicken', 'hippie crippler',
       'hoarfrost', 'hogs breath', 'hollands hope', 'hollyweed',
       'hollywood og', 'holy ghost', 'holy grail kush', 'holy roller',
       'honey bananas', 'honey boo boo', 'honey lemon cheese',
       'honey rock', 'hong kong', 'hoodwreck', 'horace', 'huckleberries',
       'huckleberry', 'huckleberry cough', 'huckleberry diesel',
       'huckleberry hound', 'hulkamania', 'humboldt', 'humboldt dream',
       'humboldt hawaiian', 'humboldt headband', 'humdinger og', 'hurkle',
       'hurricane', 'hustler kush', 'ʻalenuihāhā', 'ice', 'ice cream',
       'ice cream cake', 'ice princess', 'ice queen', 'ice wreck',
       'iced grapefruit', 'iced widow', 'ig kush', 'ill og',
       'illuminati og', 'in the pines', 'incredible bulk',
       'incredible hulk', 'industrial plant', 'ingrid', 'intergalactic',
       'inzane in the membrane', 'irene og', 'irish cream',
       'iron triangle', 'island haze', 'island maui haze',
       'island sweet skunk', 'j1', 'jack 47', 'jack burton',
       'jack diesel', 'jack flash', 'jack frost', 'jack haze',
       'jack herer', 'jack kush', 'jack of spades', 'jack skellington',
       'jack smack', 'jack the ripper', 'jack widow', 'jack wreck',
       'jackalope', 'jacks cleaner', 'jacks dream', 'jacky girl',
       'jacky white', 'jah goo', 'jah kush', 'jahwaiian', 'jamaican',
       'jamaican dream', 'jamaican lion', 'jamaican pearl', 'jamba juice',
       'jane doe', 'jawa pie', 'jazz', 'jean guy', 'jedi kush',
       'jelly roll', 'jenni', 'jenny kush', 'jericho haze', 'jesses girl',
       'jesus', 'jesus og', 'jet fuel', 'jgr', 'jilly dawg', 'jillybean',
       'jimi hendrix', 'jock horror', 'johnny’s tonic', 'jorges diamond',
       'josh d og', 'js famous kush', 'jt15', 'juicy fruit', 'juicy jack',
       'juliet', 'julius caesar', 'jungle juice', 'jungle scout cookies',
       'jupiter og', 'k1', 'k2', 'kaboom', 'kahuna', 'kaia kush',
       'kailua pua', 'kalalau kush', 'kalashnikova', 'kali 47',
       'kali china', 'kali dog', 'kali mist', 'kandahar', 'kandy kush',
       'karibbean mango', 'karma bitch', 'karma og', 'karmarado og',
       'kashmir kush', 'katsu bubba kush', 'katsu kush', 'kc 33', 'kc 36',
       'kelly hill gold', 'kens kush', 'kerala', 'kerala krush',
       'kerosene', 'ketama', 'key lime pie', 'keystone kush',
       'khalifa kush', 'khola', 'khufu', 'kid n kookies', 'kilimanjaro',
       'kill bill', 'killer grape', 'killer queen', 'killing fields',
       'kimbo kush', 'king cake', 'king kong', 'king louis xiii',
       'king thunder fuck', 'kings bread', 'kings kush', 'kiss',
       'kiwiskunk', 'kobain kush', 'koloa sunrise', 'kona gold', 'kong',
       'koolato', 'kosher kush', 'kosher tangie', 'krakatoa', 'kraken',
       'krishna kush', 'kryptonite', 'kt dawg', 'kuato', 'kubbie kush',
       'kuchi', 'kurple fantasy', 'kush cleaner', 'kush hemp',
       'kush rise', 'kushadelic', 'kushage', 'kushashima', 'kushberry',
       'la blanca', 'la blanca gold', 'la cake', 'la chocolat',
       'la confidential', 'la jack', 'la kookies', 'la kush', 'la niña',
       'la og', 'la reina de africa', 'la sunshine', 'la ultra',
       'la woman', 'lady liberty', 'ladyburn 1974', 'lak federal reserve',
       'lake of fire', 'lambo og', 'lamborghini', 'lambs bread',
       'lambs in space', 'lapd', 'larry bird kush', 'larry og',
       'las vegas purple kush bx', 'lashkar gah', 'laughing buddha',
       'laughing gas', 'lavender', 'lavender haze', 'lavender jones',
       'le silver royale', 'leagle eagle', 'leda uno', 'lee roy',
       'legalized og', 'legend of nigeria', 'legend og',
       'legendary lemon', 'lem chem', 'lemon alien dawg',
       'lemon banana sherbet', 'lemon bananas', 'lemon bubble',
       'lemon cake', 'lemon cookies', 'lemon créme', 'lemon daddy',
       'lemon diesel', 'lemon drop', 'lemon fire', 'lemon g',
       'lemon garlic og', 'lemon haze', 'lemon ice', 'lemon jack',
       'lemon jeffery', 'lemon kush', 'lemon kush headband',
       'lemon larry lavender', 'lemon marmalade', 'lemon meringue',
       'lemon og haze', 'lemon og kush', 'lemon pie', 'lemon sativa',
       'lemon skunk', 'lemon sorbet 3', 'lemon tangie', 'lemon thai',
       'lemon thai kush', 'lemon tree', 'lemon walker og', 'lemon wreck',
       'lemon zest', 'lemonberry', 'lemonchello 28', 'lemonder',
       'lemonhead og', 'lennon', 'leonidas', 'lethal purple', 'lifesaver',
       'lifestar', 'lifter', 'light of jah', 'lil sebastian',
       'lime green skunk', 'lime purple mist', 'lime skunk',
       'lime sorbet', 'lime tart', 'limon', 'lions gate', 'liquid butter',
       'little devil', 'little dragon', 'locktite', 'locomotion',
       'lodi dodi', 'logic diesel', 'longbottom leaf', 'loopy fruit',
       'lost coast hash plant', 'lost coast og',
       'lost sierra night nurse', 'loud dream', 'loud lemonade',
       'loud scout', 'love boat', 'love potion 9', 'love triangle',
       'lowryder', 'lsd', 'luca brasi x sour diesel', 'lucid bolt',
       'lucid dream', 'lucifer og', 'lucky charms', 'lucy', 'lvpk', 'mac',
       'mad dawg', 'mad scientist', 'madagascar', 'madcow', 'madman og',
       'madzilla', 'mag 91', 'mag landrace', 'magellan', 'magic beans og',
       'magic jordan', 'magic melon', 'magnificent mile', 'magnum',
       'magnum opus', 'magnum pi', 'mai tai cookies', 'majestic 12',
       'mako haze', 'malakoff', 'malawi', 'malawi gold', 'mammoth',
       'mandala 1', 'mandarin cookies', 'mandarin dreams',
       'mandarin sunset', 'mandarin zkittlez', 'mango', 'mango dream',
       'mango habanero', 'mango kush', 'mango sapphire', 'mango sherbert',
       'mango tango', 'mangolicious', 'manitoba poison',
       'maple leaf indica', 'maramota 10', 'marcosus marshmellow',
       'marionberry kush', 'marionberry pie', 'marleys collie',
       'marmalade', 'mars og', 'martian candy', 'martian mean green',
       'martian muffins', 'master bubba', 'master jedi', 'master kush',
       'master og', 'master skunk', 'master yoda',
       'matanuska thunder fuck', 'mataro blue', 'matsu', 'maui',
       'maui berry', 'maui bubble gift', 'maui citrus punch',
       'maui haole', 'maui mango diesel', 'maui wowie', 'mazar i sharif',
       'mazar kush', 'mazar x blueberry', 'mazari', 'mc1', 'mean misty',
       'medibud', 'medicine man', 'medicine woman', 'medihaze', 'medusa',
       'mega jackpot', 'megalodon', 'mekamika haze', 'melon gum',
       'member berry', 'memory loss', 'mendo afgoo', 'mendo breath',
       'mendo queen', 'mendo supremo', 'mendocino madness',
       'mendocino purps', 'mercury og', 'merlot og', 'mexican',
       'mexican sativa', 'michael phelps og', 'michka', 'mickey kush',
       'middlefork', 'middlefork x pineapple express', 'midnight',
       'mighty glue', 'milf', 'milky way', 'millennium', 'mimosa',
       'mint chocolate chip', 'mission kush', 'misty kush',
       'misty morning', 'mk ultra', 'mob boss', 'moby dick', 'mochi',
       'money maker', 'monkey bread 1', 'monkey paw', 'monkey thunder',
       'monolith', 'monster cookies', 'monster og', 'montana silvertip',
       'moon cookies', 'moon drops', 'moon walk', 'moonbeam', 'moondance',
       'moonshine haze', 'moonwalker kush', 'moose and lobsta',
       'more cowbell', 'morning glory', 'morning star', 'mossad',
       'mossimo og', 'motavation', 'mother of all cherries',
       'mother of berries', 'mother tongue', 'mothers finest',
       'mothers helper', 'mothers milk', 'motorbreath', 'mountain girl',
       'mountain girl x grape ape', 'mountain thunder',
       'mozambique poison', 'mr nice', 'mr tusk', 'ms universe',
       'mt cook', 'mt hood magic', 'mt rainier', 'mud bite', 'murkle',
       'mystery 98', 'mystery jazz', 'nanas fix', 'narnia', 'nebula',
       'nebula ii cbd', 'nectarine lips', 'negra 44', 'neil haze',
       'nepalese', 'nepalese jam', 'neptune kush', 'neptune og',
       'nevilles haze', 'nevils wreck', 'new glue', 'nice cherry',
       'nicole kush', 'night nurse', 'night terror og', 'night train',
       'nightfire og', 'nightmare cookies', 'nightmare og', 'nina limone',
       'ninja fruit', 'nl5 haze mist', 'nor cal purps', 'nordle',
       'north american sativa', 'north indian', 'northern berry',
       'northern cross', 'northern lights', 'northern lights 5',
       'northern lights 5 x haze', 'northern skunk', 'northern wreck',
       'northwest pineapple', 'nova', 'nuclear cookies', 'nuggetry og',
       'nukeheads', 'nuken', 'nurse jackie', 'ny cheese', 'nyc diesel',
       'nypd', 'obama kush', 'oca gold', 'ocd', 'ocean view', 'odyssey',
       'og 1 kenobi', 'og 18', 'og cheese', 'og chem', 'og diesel kush',
       'og eddy lepp', 'og glue sniffer', 'og kush', 'og la affie',
       'og lime killer', 'og los angeles kush', 'og poison',
       'og purple fire thai', 'og ringo', 'og shark', 'og skunk',
       'og sour diesel', 'og strawberry', 'og tonic', 'og wreck',
       'ogiesel', 'ogkb', 'ogkz', 'ogre', 'ogre berry', 'ogs pearl',
       'ol betsy', 'old lyme connecticut og', 'old mother sativa',
       'old school og', 'old toby', 'omega', 'omega dawg', 'one to one',
       'opal og kush', 'opium', 'or', 'orange afghani', 'orange blossom',
       'orange bud', 'orange cream', 'orange creamsicle', 'orange crush',
       'orange diesel', 'orange dream', 'orange durban', 'orange harambe',
       'orange haze', 'orange hill special', 'orange juice',
       'orange kush', 'orange kush breath', 'orange romulan',
       'orange skunk', 'orange snow cone', 'orange turbo',
       'orange velvet', 'orange wreck', 'orangutang', 'oregon diesel',
       'oregon pineapple', 'oregon pinot noir', 'organic diesel',
       'orient express', 'original glue', 'ortega', 'outer space',
       'outlaw', 'pacific blue', 'pacific frost', 'pagoda',
       'pakistan valley kush', 'pakistani chitral kush', 'palm tree cbd',
       'pamelina', 'pan jam', 'panama punch', 'panama red', 'panda og',
       'pandoras box', 'papas og', 'paris og', 'paris xxx', 'patti cake',
       'peach cobbler', 'peach puree', 'peaches and cream', 'peachy mack',
       'pearl scout cookies', 'peles fire og', 'pennywise',
       'peppermint cookies', 'perfect purple', 'permafrost', 'pestilence',
       'petrolia headstash', 'peyote cookies', 'peyton manning', 'pez',
       'phantom arrow', 'phantom cookies', 'phantom og', 'phatt frutty',
       'pheno 51', 'phishhead kush', 'pie face og', 'pie hoe',
       'pine cone', 'pine queen dream', 'pine tar kush', 'pineapple',
       'pineapple cookies', 'pineapple diesel', 'pineapple dog shit',
       'pineapple express', 'pineapple fields', 'pineapple haze',
       'pineapple jack', 'pineapple kush', 'pineapple mayhem',
       'pineapple og', 'pineapple punch', 'pineapple purple skunk',
       'pineapple purps', 'pineapple sage', 'pineapple skunk',
       'pineapple super silver haze', 'pineapple thai',
       'pineapple trainwreck', 'pineapple upside down cake',
       'pineapple zest', 'pineberry', 'pinewarp', 'pink berry',
       'pink bubba', 'pink champagne', 'pink cookies', 'pink death star',
       'pink hawaiian', 'pink kush', 'pink lemonade', 'pink mango',
       'pink panther', 'pink panties', 'pink pez', 'pink starburst',
       'pink sunset', 'pinkman goo', 'pinot green', 'pitbull', 'placenta',
       'platinum bubba kush', 'platinum calyx', 'platinum gsc',
       'platinum huckleberry cookies', 'platinum kush', 'platinum og',
       'platinum purple kush', 'platinum sour diesel', 'platinum wreck',
       'plushberry', 'pluto kush', 'poison haze', 'pokie', 'poochie love',
       'pop rox', 'popcorn kush', 'pot of gold', 'powderhound',
       'power kush', 'power plant', 'predator pink', 'presidential og',
       'prevention', 'primus', 'princess', 'princesss tiara',
       'professor chaos', 'project blue book', 'puna buddaz',
       'puna budder', 'punky lion', 'punxsy punch', 'pura vida',
       'pure afghan', 'pure kush', 'pure love', 'pure og',
       'pure power plant', 'purple afghani', 'purple alien og',
       'purple arrow', 'purple aurora', 'purple berry', 'purple bubba',
       'purple bud', 'purple buddha', 'purple bush', 'purple candy',
       'purple champagne', 'purple cheddar', 'purple cheese',
       'purple chemdawg', 'purple cotton candy', 'purple cow',
       'purple crack', 'purple cream', 'purple diesel', 'purple dog shit',
       'purple dragon', 'purple dream', 'purple elephant', 'purple frost',
       'purple glue', 'purple goat', 'purple goo', 'purple gorilla',
       'purple happy rancher', 'purple hashplant', 'purple haze',
       'purple headband', 'purple hindu kush', 'purple ice',
       'purple jack', 'purple killer', 'purple kush', 'purple linda',
       'purple martian kush', 'purple maui', 'purple monkey balls',
       'purple mr nice', 'purple nepal', 'purple og kush',
       'purple pantera', 'purple panty dropper', 'purple paralysis',
       'purple passion', 'purple people eater', 'purple pie',
       'purple pinecone', 'purple power', 'purple prevention',
       'purple princess', 'purple punch', 'purple raine', 'purple rhino',
       'purple sage ', 'purple skunk', 'purple sour diesel',
       'purple star', 'purple swish', 'purple tangie', 'purple tears',
       'purple thai', 'purple tonic', 'purple trainwreck', 'purple urkle',
       'purple voodoo', 'purple widow', 'purple wreck', 'pvc og', 'q3',
       'qleaner', 'qrazy train', 'quad dawg', 'quantum kush',
       'quebec gold', 'queen mother goji', 'queens panties', 'querkle',
       'qush', 'race fuel og', 'rainbow', 'rainbow jones', 'raindance',
       'ramses', 'rare dankness 1', 'rare darkness', 'raskal og',
       'raspberry cough', 'raspberry diesel', 'raspberry kush',
       'raw diesel', 'ray charles', 'rebel berry og', 'rebel god smoke',
       'rebel tangie kandy', 'reclining buddha', 'recon',
       'red cherry berry', 'red congolese', 'red diesel', 'red dragon',
       'red dwarf', 'red eye og', 'red haze', 'red headed stranger',
       'red poison', 'red rhino', 'red velvet pie', 'red widow',
       'redd cross', 'redding og', 'redwood kush', 'remedy', 'remo chemo',
       'rene', 'rene mist', 'richie rich', 'riddler og', 'ridge berry',
       'ringos gift', 'rip city purps', 'ripped bubba', 'rise ‘n’ shine',
       'river song', 'road dawg', 'rob ford kush', 'robert plant',
       'rockbud', 'rocket fuel', 'rocklock', 'rockstar', 'rockstar kush',
       'rockstar master kush', 'rocky dennis', 'rocky mountain blueberry',
       'rocky mountain high', 'rollex og kush', 'rolls choice',
       'romping goddess', 'romulan', 'romulan grapefruit', 'romulan haze',
       'root beer kush', 'rose bud', 'royal chemdawg', 'royal dwarf',
       'royal haze', 'royal highness', 'royal kush', 'royal tree sherbet',
       'rozé', 'rubicon', 'rudeboi og', 'rug burn og', 'russian assassin',
       'russian doll', 'russian rocket fuel', 'russian roulette',
       'safety meeting', 'sage', 'sage n sour', 'sage walker',
       'salmon river og', 'santa maria', 'santa sativa', 'sapphire scout',
       'sapphire star', 'sasquatch sap', 'satellite og', 'satori',
       'satsuma', 'saturn og', 'savage citrus sunshine', 'savants grail',
       'schrom', 'scooby snacks', 'scotts og', 'scouts honor',
       'scroopy noopers', 'seattle blue', 'seattle cough',
       'seattle summer', 'seattlesoda', 'secret garden og',
       'secret recipe', 'sensi skunk', 'sensi star', 'sequoia strawberry',
       'serious 6', 'serious happiness', 'sexxpot', 'sfv dog', 'sfv og',
       'sfv og kush', 'shaman', 'shark attack', 'shark bite',
       'shark shock', 'sherbert', 'shiatsu kush', 'shining silver haze',
       'shipwreck', 'shishkaberry', 'shiskaquine', 'shiva skunk',
       'shoreline', 'shurman', 'sidetracked', 'sierra mist',
       'silver back', 'silver bubble', 'silver calyx', 'silver cindy',
       'silver haze', 'silver kush', 'silver mountain', 'silver nina',
       'silver pearl', 'silver surfer', 'silver train',
       'silverback gorilla', 'silverfalls kush', 'silverhawks og',
       'sin city kush', 'sin valley og', 'sinai', 'sinmint cookies',
       'sirius black', 'sister glue', 'six shooter', 'sizzurp',
       'skins skunk', 'skunk 47', 'skunk dawg', 'skunk haze', 'skunk+',
       'skunkberry', 'skunky diesel', 'sky lotus', 'sky master', 'skydog',
       'skywalker alien', 'slazerbeam', 'sleeskunk', 'sleestack',
       'slice of heaven', 'slimer og', 'smelliot', 'smooth operator',
       'snoop dogg og', 'snoops dream', 'snow bud', 'snow diesel',
       'snow goddess', 'snow leopard', 'snow lotus', 'snow monster',
       'snow mountain', 'snow ryder', 'snow white', 'snowcap', 'snowland',
       'sojay haze', 'somango', 'sonic screwdriver', 'sonoma coma',
       'sorbet dreams', 'sorbetto', 'sorcerer’s apprentice',
       'soul assassin og', 'soul shine', 'soulshine aloha', 'sour alien',
       'sour amnesia', 'sour ape', 'sour apple', 'sour banana sherbet',
       'sour blueberry', 'sour boggle', 'sour breath', 'sour bubba',
       'sour bubble', 'sour candy', 'sour cheese', 'sour cherry sherbert',
       'sour chocolate', 'sour chunk', 'sour cookies', 'sour cream',
       'sour diesel', 'sour dream', 'sour dubble', 'sour flower',
       'sour grape', 'sour haze', 'sour headband', 'sour jack',
       'sour jilly', 'sour joker', 'sour kush', 'sour lemon og',
       'sour lifesavers', 'sour lsd', 'sour maui', 'sour og',
       'sour patch kiss', 'sour pebbles', 'sour poison', 'sour power',
       'sour power og', 'sour space candy', 'sour spyder',
       'sour star head', 'sour strawberry', 'sour strawberry diesel',
       'sour sunset', 'sour tangie', 'sour tsunami', 'sour urkle',
       'sour willie', 'sourlope', 'south american', 'south asian sativa',
       'south central la', 'southern lights', 'space bomb', 'space cake',
       'space candy', 'space cream', 'space dawg', 'space jill',
       'space monster', 'space needle', 'space queen', 'special k',
       'special kush 1', 'special sauce', 'spicy disco', 'spiked punch',
       'spirit of 76', 'spoetnik 1', 'spumoni', 'sputnik', 'spyder mon',
       'star 47', 'star berry indica', 'star killer', 'star master kush',
       'star pupil', 'star tonic', 'starbud', 'stardawg', 'stardawg 91',
       'stardawg guava', 'starfighter', 'starman', 'starry night',
       'stella blue', 'stephen hawking kush', 'stevie wonder',
       'stinky pete', 'stoopid fruits', 'straight as haze', 'strawberry',
       'strawberry alien kush', 'strawberry amnesia', 'strawberry banana',
       'strawberry blonde', 'strawberry blondie', 'strawberry blue',
       'strawberry cheesecake', 'strawberry cough', 'strawberry diesel',
       'strawberry dream', 'strawberry durban diesel',
       'strawberry fields', 'strawberry frost', 'strawberry ice',
       'strawberry kush', 'strawberry lemonade', 'strawberry milkshake',
       'strawberry og', 'strawberry satori', 'strawberry shortcake',
       'strawberry snow cone', 'sublime', 'sugar black rose',
       'sugar cookie', 'sugar kush', 'sugar mama', 'sugar pine',
       'sugar plum', 'sugar plum sunset', 'sugar punch', 'sugar shack',
       'suicide girl', 'summer breeze', 'summertime squeeze',
       'sumo grande', 'sun ra', 'sunburn', 'sundae driver', 'sunny d',
       'sunset', 'sunset haze', 'sunshine', 'sunshine 4',
       'sunshine daydream', 'supa don', 'super  chronic',
       'super blue dream', 'super bud', 'super cat piss', 'super cheese',
       'super g', 'super glu', 'super green crack', 'super jack',
       'super kush', 'super lemon haze', 'super lemon og',
       'super silver hash plant', 'super silver haze',
       'super silver lights', 'super snow dog', 'super snow lotus',
       'super sour diesel', 'super sour lemon', 'super sour og',
       'super sour skunk', 'super sour widow', 'super sweet', 'supergirl',
       'superglue', 'superman og', 'supermax og', 'supernatural',
       'supernova', 'superstar', 'suver haze', 'suzy q', 'swazi gold',
       'sweet amnesia haze', 'sweet and sour widow', 'sweet baby jane',
       'sweet berry', 'sweet black angel', 'sweet cheese', 'sweet cindy',
       'sweet deep grapefruit', 'sweet diesel', 'sweet dream',
       'sweet dreams', 'sweet harlem diesel',
       'sweet hawaiian tangie banana', 'sweet jane', 'sweet jesus',
       'sweet kush', 'sweet lafayette', 'sweet nina', 'sweet pebbles',
       'sweet pure cbd', 'sweet skunk', 'sweet tooth',
       'sweet valley kush', 'sweeties', 'swiss bliss', 'swiss gold',
       'swiss tsunami', 'tahoe alien', 'tahoe frostbite',
       'tahoe hydro champagne', 'tahoe hydro og', 'tahoe purps',
       'taliban poison', 'tangelo', 'tangelo kush', 'tangerine',
       'tangerine dream', 'tangerine haze', 'tangerine kush',
       'tangerine man', 'tangerine power', 'tangerine sunrise',
       'tangerine trainwreck haze', 'tangie', 'tangie biscotti',
       'tangie cookies', 'tangie dream', 'tangie ghost train',
       'tangie sunrise', 'tangier chilly', 'tangilope', 'tango kush',
       'tardis', 'tembo kush', 'terminator og', 'tesla', 'tesla tower',
       'thai', 'thai fantasy', 'thai girl', 'thai haze', 'thai lights',
       'thaidal wave', 'thc bomb', 'the big dirty', 'the black',
       'the blintz', 'the blood', 'the brotherhood', 'the cbg blend',
       'the cough', 'the doctor', 'the flav', 'the forbidden candy',
       'the fuzz', 'the gift', 'the grunk', 'the guice', 'the hog',
       'the lime', 'the loops', 'the one', 'the ooze',
       'the original lemonnade', 'the ox', 'the real mccoy', 'the sauce',
       'the sheriff', 'the sister', 'the third dimension', 'the truth',
       'the vision', 'the void', 'the white angel', 'the wife',
       'the wills', 'thelonious skunk', 'think different', 'thors hammer',
       'three blue kings', 'throwback kush', 'thunderbird rose',
       'thunderstruck', 'tickle kush', 'tiger woods', 'tigermelon',
       'tigers milk', 'tillamook strawberry', 'timewreck', 'tina',
       'tina danza', 'titans haze', 'tjs cbd', 'tokyo og',
       'tommys home grown', 'tora bora', 'toxic', 'toxic punch',
       'training day', 'trainwreck', 'tranquil elephantizer: remix',
       'transformer', 'trap star', 'trash', 'travel joint',
       'treasure island', 'tree of life', 'tres dawg', 'triangle kush',
       'trident', 'trifecta', 'trinity', 'triple cheese', 'triple diesel',
       'trix', 'trophy wife', 'tropic thunder', 'tropical tang',
       'tropicali', 'tropicana cookies', 'tropicana punch', 'true face',
       'true og', 'true x', 'trueberry', 'truffle butter',
       'truffula tree', 'truth serum', 'tuna kush', 'tuna og',
       'turbo mind warp', 'tutankhamon', 'tutti frutti', 'twista',
       'twisted citrus', 'two beards', 'tyson', 'u2 kush', 'uk cheese',
       'ultimate trainwreck', 'ultra banana', 'ultra sonja', 'ultra sour',
       'ultraviolet og', 'urkle train haze', 'uw', 'vader og',
       'valentine x', 'valley ghash', 'valley girl', 'vanilla frosting',
       'vanilla gorilla', 'vanilla kush', 'vanilluna', 'vcdc',
       'velvet bud', 'velvet purps', 'venice og', 'venom og', 'venus og',
       'verde electric', 'versace', 'very berry haze', 'very cherry',
       'vietnamese bubba', 'violator kush', 'violet delight', 'violeta',
       'viper', 'vixen', 'voodoo', 'vortex', 'wabanaki', 'waipio hapa',
       'wakanda og', 'waldo', 'walker kush', 'wally og', 'walrus kush',
       'walter white', 'wappa', 'warlock', 'washing machine',
       'watermelon', 'webster', 'wedding cake', 'wedding crasher',
       'weebe’s world', 'wellness og', 'wembley', 'west coast dawg',
       'west og', 'wet dream', 'wheres my bike', 'whitaker blues',
       'white 99', 'white bastard', 'white berry', 'white bubblegum',
       'white buffalo', 'white castle', 'white cheese',
       'white cherry truffle', 'white choco', 'white chocolate',
       'white cookies', 'white dawg', 'white dawg fire og',
       'white diesel', 'white domina', 'white dragon', 'white dream',
       'white durban', 'white elephant', 'white empress', 'white fire 43',
       'white fire alien og', 'white girl', 'white gold', 'white gorilla',
       'white harmony', 'white haze', 'white ice', 'white knight',
       'white kryptonite', 'white kush', 'white lavender', 'white lemon',
       'white lightning', 'white lotus', 'white lsd', 'white master',
       'white moonshine', 'white nightmare', 'white og', 'white queen',
       'white rhino', 'white romulan', 'white russian', 'white sangria',
       'white siberian', 'white skunk', 'white slipper', 'white smurf',
       'white strawberry', 'white strawberry skunk',
       'white tahoe cookies', 'white tygh dream', 'white urkle',
       'white walker kush', 'white walrus', 'white widow', 'white zombie',
       'whiteout', 'whitewalker og', 'wild thailand', 'willie nelson',
       'willie’s ghost', 'willy wonka', 'willys wonder', 'wish mountain',
       'wmd', 'wolfberry', 'wonder haze', 'wonder kid', 'wonder woman',
       'wonkas bubblicious', 'woody kush', 'wookie', 'wookies',
       'wreckage', 'wsu', 'wtf', 'xanadu', 'xxx 420', 'xxx og',
       'y griega', 'yem og', 'yeti og', 'yoda og', 'yodas brain',
       'yogi diesel', 'yolo berry', 'yumboldt', 'yummy', 'zamaldelica',
       'zelda', 'zen', 'zerculese', 'zeta sage', 'zeus og', 'zkittlez',
       'zombie kush', 'zombie og', 'zoom pie']
